## Bayes Classifier

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:

df =  pd.read_csv("data.csv")
df = df.dropna()



In [3]:
df.drop(df.columns[0], axis=1, inplace=True)
df

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10  ...  X170  X171  \
0      135  190  229  223  192  125   55   -9  -33  -38  ...   -17   -15   
1      386  382  356  331  320  315  307  272  244  232  ...   164   150   
2      -32  -39  -47  -37  -32  -36  -57  -73  -85  -94  ...    57    64   
3     -105 -101  -96  -92  -89  -95 -102 -100  -87  -79  ...   -82   -81   
4       -9  -65  -98 -102  -78  -48  -16    0  -21  -59  ...     4     2   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
11495  -22  -22  -23  -26  -36  -42  -45  -42  -45  -49  ...    15    16   
11496  -47  -11   28   77  141  211  246  240  193  136  ...   -65   -33   
11497   14    6  -13  -16   10   26   27   -9    4   14  ...   -65   -48   
11498  -40  -25   -9  -12   -2   12    7   19   22   29  ...   121   135   
11499   29   41   57   72   74   62   54   43   31   23  ...   -59   -25   

       X172  X173  X174  X175  X176  X177  X178  y  
0       -31   -77  -103  -127  -116   -83   -51  4  
1       146   152   157   156   154   143   129  1  
2        48    19   -12   -30   -35   -35   -36  5  
3       -80   -77   -85   -77   -72   -69   -65  5  
4       -12   -32   -41   -65   -83   -89   -73  5  
...     ...   ...   ...   ...   ...   ...   ... ..  
11495    12     5    -1   -18   -37   -47   -48  2  
11496    -7    14    27    48    77   117   170  1  
11497   -61   -62   -67   -30    -2    -1    -8  5  
11498   148   143   116    86    68    59    55  3  
11499    -4     2     5     4    -2     2    20  4  

[11500 rows x 179 columns]

In [4]:
df.shape

(11500, 179)

In [39]:
df['y'].value_counts() 

5    2300
4    2300
3    2300
2    2300
1    2300
Name: y, dtype: int64

In [40]:
df.corr()

X1        X2        X3        X4        X5        X6        X7  \
X1    1.000000  0.947729  0.808192  0.608109  0.393674  0.218226  0.103693   
X2    0.947729  1.000000  0.944623  0.790403  0.576579  0.369803  0.211793   
X3    0.808192  0.944623  1.000000  0.939522  0.778648  0.573874  0.382493   
X4    0.608109  0.790403  0.939522  1.000000  0.938636  0.784954  0.590497   
X5    0.393674  0.576579  0.778648  0.938636  1.000000  0.941267  0.792304   
...        ...       ...       ...       ...       ...       ...       ...   
X175  0.036144  0.024290  0.015536  0.016992  0.021924  0.022444  0.014869   
X176  0.030581  0.023906  0.016982  0.016911  0.018869  0.020977  0.017016   
X177  0.024562  0.021962  0.017070  0.014671  0.013607  0.017383  0.018572   
X178  0.020022  0.018059  0.012419  0.006226  0.001298  0.004240  0.008325   
y     0.022375  0.019154  0.013469  0.004763 -0.006597 -0.018256 -0.026422   

            X8        X9       X10  ...      X170      X171      X172  \
X1    0.044483  0.027923  0.032221  ...  0.027263  0.045401  0.051630   
X2    0.109478  0.060218  0.043565  ...  0.012602  0.025937  0.031606   
X3    0.231084  0.133249  0.080003  ...  0.004575  0.011752  0.016424   
X4    0.399855  0.250052  0.150284  ... -0.001028  0.000632  0.006617   
X5    0.596424  0.410651  0.265112  ...  0.004861  0.000918  0.006488   
...        ...       ...       ...  ...       ...       ...       ...   
X175 -0.000510 -0.018552 -0.036517  ...  0.195640  0.366428  0.573335   
X176  0.005851 -0.009052 -0.025522  ...  0.084966  0.195891  0.359400   
X177  0.012590  0.001943 -0.011809  ...  0.022042  0.071946  0.175322   
X178  0.008032  0.004823 -0.001332  ... -0.004094  0.001945  0.049854   
y    -0.027478 -0.029452 -0.034459  ...  0.002707  0.012589  0.022893   

          X173      X174      X175      X176      X177      X178         y  
X1    0.049604  0.042967  0.036144  0.030581  0.024562  0.020022  0.022375  
X2    0.030452  0.025975  0.024290  0.023906  0.021962  0.018059  0.019154  
X3    0.017070  0.014837  0.015536  0.016982  0.017070  0.012419  0.013469  
X4    0.011882  0.014496  0.016992  0.016911  0.014671  0.006226  0.004763  
X5    0.013946  0.019146  0.021924  0.018869  0.013607  0.001298 -0.006597  
...        ...       ...       ...       ...       ...       ...       ...  
X175  0.782018  0.936986  1.000000  0.933893  0.759069  0.533265  0.028425  
X176  0.563321  0.767300  0.933893  1.000000  0.931826  0.759381  0.027259  
X177  0.337020  0.537493  0.759069  0.931826  1.000000  0.934330  0.026156  
X178  0.155044  0.315385  0.533265  0.759381  0.934330  1.000000  0.025168  
y     0.029172  0.028563  0.028425  0.027259  0.026156  0.025168  1.000000  

[179 rows x 179 columns]

In [46]:
X_TRAIN, X_TEST, Y_TRAIN, Y_TEST = train_test_split(df.iloc[:, 0:5].values, df.iloc[:, -1].values, train_size = 0.7, random_state = 101)

In [7]:
X_TRAIN.shape

(8049, 5)

In [8]:
X_TEST.shape


(3451, 5)

In [9]:
X_TRAIN = np.transpose(X_TRAIN) # Converting features in column format
X_TEST = np.transpose(X_TEST)
X_TEST

array([[  6,  91, 101, ..., -45,  22,  42],
       [  7, 101,  96, ..., -59,  26,  44],
       [ -1, 100,  91, ..., -62,  22,  36],
       [-13,  97,  84, ..., -53,  15,  28],
       [-21, 106,  79, ..., -26,   7,  37]], dtype=int64)

In [10]:
Y_TRAIN = np.transpose(Y_TRAIN).reshape(1,8049)
Y_TEST = np.transpose(Y_TEST).reshape(1,3451)

In [11]:
Total_Train_sample = 8049
no_of_c1 = np.sum(Y_TRAIN == 1)
no_of_c2 = np.sum(Y_TRAIN == 2)
no_of_c3 = np.sum(Y_TRAIN == 3)
no_of_c4 = np.sum(Y_TRAIN == 4)
no_of_c5 = np.sum(Y_TRAIN == 5)

print(no_of_c1,no_of_c2,no_of_c3,no_of_c4,no_of_c5)


1631 1608 1613 1615 1582


In [12]:
# Calculating prior for each class
prior_c1 =  no_of_c1/Total_Train_sample
prior_c2 =  no_of_c2/Total_Train_sample
prior_c3 =  no_of_c3/Total_Train_sample
prior_c4 =  no_of_c4/Total_Train_sample
prior_c5 =  no_of_c5/Total_Train_sample
print(prior_c1,prior_c2,prior_c3,prior_c4,prior_c5)

0.20263386756118773 0.19977636973537086 0.20039756491489627 0.20064604298670644 0.19654615480183873


In [ ]:
#Y_TRAIN.shape

In [14]:
full_train  = np.append(X_TRAIN, Y_TRAIN, axis=0)
full_train

array([[  32, -219, -135, ...,   44, -925,   23],
       [  52, -221, -145, ...,   52, -759,   14],
       [  38, -203, -151, ...,   55, -443,   12],
       [  24, -165, -155, ...,   57,  -60,    9],
       [ -24, -136, -165, ...,   49,  313,   11],
       [   4,    4,    1, ...,    3,    1,    3]], dtype=int64)

In [15]:

c1_index = [index for index, value in enumerate(full_train[5,:]) if value == 1]
c2_index = [index for index, value in enumerate(full_train[5,:]) if value == 2]
c3_index = [index for index, value in enumerate(full_train[5,:]) if value == 3]
c4_index = [index for index, value in enumerate(full_train[5,:]) if value == 4]
c5_index = [index for index, value in enumerate(full_train[5,:]) if value == 5]

In [17]:
# Dividing train data as per class

c1_train_data = X_TRAIN[:,c1_index]
c2_train_data = X_TRAIN[:,c2_index]
c3_train_data = X_TRAIN[:,c3_index]
c4_train_data = X_TRAIN[:,c4_index]
c5_train_data = X_TRAIN[:,c5_index]
c5_train_data

array([[  24,   44,   30, ...,  -86,    4,  -45],
       [  11,   72,   33, ...,  -90,   -6,  -26],
       [ -18,   80,   26, ...,  -98,   -6,  -12],
       [ -33,   89,   16, ..., -109,    3,    3],
       [ -13,   96,   13, ..., -110,   13,   29]], dtype=int64)

In [21]:
# Calculating mean for all the three class

c1_mean = np.mean(c1_train_data, axis=1).reshape(5,1)
c2_mean = np.mean(c2_train_data, axis=1).reshape(5,1)
c3_mean = np.mean(c3_train_data, axis=1).reshape(5,1)
c4_mean = np.mean(c4_train_data, axis=1).reshape(5,1)
c5_mean = np.mean(c5_train_data, axis=1).reshape(5,1)

In [23]:
#Calculating covarience for all the three classes

c1_cov = np.cov(c1_train_data)
c2_cov = np.cov(c2_train_data)
c3_cov = np.cov(c3_train_data)
c4_cov = np.cov(c4_train_data)
c5_cov = np.cov(c5_train_data)
c5_cov

array([[2193.39980417, 2102.78244338, 1849.79256036, 1548.3535521 ,
        1276.92344977],
       [2102.78244338, 2244.46087907, 2137.07053418, 1880.02140222,
        1553.62234771],
       [1849.79256036, 2137.07053418, 2288.96218767, 2184.30202603,
        1909.71425293],
       [1548.3535521 , 1880.02140222, 2184.30202603, 2327.75948587,
        2198.6219415 ],
       [1276.92344977, 1553.62234771, 1909.71425293, 2198.6219415 ,
        2319.89432227]])

In [24]:
# Calculating the likelihood by gaussian distribution formula

def likelihood(x, mu, cov, k):
    numerator = np.exp(-0.5 * np.matmul(np.matmul(np.transpose(x - mu), np.linalg.inv(cov)), (x - mu)))
    denominator = np.sqrt(((2 * np.pi) ** k) * np.linalg.det(cov))
    return numerator/denominator

In [25]:
X_TRAIN.shape[1]

8049

In [31]:
predictions =[]
for i in range(X_TRAIN.shape[1]):
    sample = np.array(X_TRAIN[[0,1,2,3,4],i]).reshape(5,1)
    C1_posterior = prior_c1 * likelihood(sample, c1_mean, c1_cov, 2)
    C2_posterior = prior_c2 * likelihood(sample, c2_mean, c2_cov, 2)
    C3_posterior = prior_c3 * likelihood(sample, c3_mean, c3_cov, 2)
    C4_posterior = prior_c4 * likelihood(sample, c4_mean, c4_cov, 2)
    C5_posterior = prior_c5 * likelihood(sample, c5_mean, c5_cov, 2)
    
    if   C1_posterior > C2_posterior and C1_posterior > C3_posterior and C1_posterior > C4_posterior and C1_posterior > C5_posterior :
             sample_class = 1
    elif C2_posterior > C1_posterior and C2_posterior > C3_posterior and C2_posterior > C4_posterior and C2_posterior > C5_posterior:
            sample_class = 2
    elif C3_posterior > C1_posterior and C3_posterior > C2_posterior and C3_posterior > C4_posterior and C3_posterior > C5_posterior:
            sample_class = 3
    elif C4_posterior > C1_posterior and C4_posterior > C2_posterior and C4_posterior > C3_posterior and C4_posterior > C5_posterior:
            sample_class = 4
    else:
            sample_class = 5
    
    predictions.append(sample_class)
    

In [32]:
#train_result = predictions ==Y_TRAIN
train_correct_predict = np.count_nonzero(Y_TRAIN)
#correct_predict

In [33]:
# Training accuracy ( total no of samples correctly predicted / total no.of samples)
train_accuracy = train_correct_predict/105
print('Training data accuracy is {} '.format(train_accuracy))

Training data accuracy is 76.65714285714286 


In [64]:
# Checking on the Test Data

In [36]:
predictions =[]
for i in range(X_TEST.shape[1]):
    sample = np.array(X_TEST[[0,1,2,3,4],i]).reshape(5,1)
    C1_posterior = prior_c1 * likelihood(sample, c1_mean, c1_cov, 2)
    C2_posterior = prior_c2 * likelihood(sample, c2_mean, c2_cov, 2)
    C3_posterior = prior_c3 * likelihood(sample, c3_mean, c3_cov, 2)
    C4_posterior = prior_c4 * likelihood(sample, c4_mean, c4_cov, 2)
    C5_posterior = prior_c5 * likelihood(sample, c5_mean, c5_cov, 2)
    
    if   C1_posterior > C2_posterior and C1_posterior > C3_posterior and C1_posterior > C4_posterior and C1_posterior > C5_posterior :
             sample_class = 1
    elif C2_posterior > C1_posterior and C2_posterior > C3_posterior and C2_posterior > C4_posterior and C2_posterior > C5_posterior:
            sample_class = 2
    elif C3_posterior > C1_posterior and C3_posterior > C2_posterior and C3_posterior > C4_posterior and C3_posterior > C5_posterior:
            sample_class = 3
    elif C4_posterior > C1_posterior and C4_posterior > C2_posterior and C4_posterior > C3_posterior and C4_posterior > C5_posterior:
            sample_class = 4
    else:
            sample_class = 5
    
    predictions.append(sample_class)
    

In [37]:
#test_result = test_predictions ==Y_TEST
test_correct_predict = np.count_nonzero(Y_TEST)

In [38]:
test_accuracy = test_correct_predict/45
print('Test data accuracy is {} '.format(test_accuracy))

Test data accuracy is 76.68888888888888 


In [41]:
#Naive Bayes Classifier

In [45]:

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:, 0:178].values, df.iloc[:, -1].values, train_size = 0.8, random_state = 101)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, Y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"
      % (X_test.shape[0], (Y_test != y_pred).sum()))


Number of mislabeled points out of a total 2300 points : 1306


In [46]:
print('Accuracy of GNB classifier on training set: {:.2f}'
     .format(gnb.score(X_train, Y_train)))
print('Accuracy of GNB classifier on test set: {:.2f}'
     .format(gnb.score(X_test, Y_test)))

Accuracy of GNB classifier on training set: 0.44
Accuracy of GNB classifier on test set: 0.43
